# Generated by Django 3.1.8 on 2021-04-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.PositiveIntegerField(default=0)),
                ('payment_status', models.BooleanField(choices=[(True, 'Paid'), (False, 'Unpaid')], default=True, null=True)),
                ('current_month_payment', models.FloatField(default=0)),
                ('debt', models.FloatField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.building')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.tenant')),
            ],
        ),
    ]
