# Generated by Django 3.1.8 on 2021-04-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
        ('apartment', '0003_mutualutil'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_payment', models.FloatField(default=0, null=True)),
                ('index_counter', models.IntegerField(default=0, null=True)),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Disabled')], default=False, null=True)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('util', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residential.utility')),
            ],
        ),
    ]
