# Generated by Django 3.1.7 on 2021-04-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_auto_20210414_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='current_month_payment',
        ),
    ]
