# Generated by Django 3.1.7 on 2021-04-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_remove_apartment_current_month_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualutil',
            name='monthly_payment',
        ),
        migrations.RemoveField(
            model_name='mutualutil',
            name='monthly_payment',
        ),
    ]
