# Generated by Django 3.1.7 on 2021-04-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_auto_20210419_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualutil',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='individualutil',
            name='index_counter',
        ),
        migrations.RemoveField(
            model_name='individualutil',
            name='status',
        ),
        migrations.RemoveField(
            model_name='individualutil',
            name='util',
        ),
        migrations.RemoveField(
            model_name='mutualutil',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='mutualutil',
            name='util',
        ),
    ]
