# Generated by Django 3.1.7 on 2021-04-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0007_mainutil'),
        ('apartment', '0010_auto_20210420_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualutil',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment'),
        ),
        migrations.AddField(
            model_name='individualutil',
            name='index_counter',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='individualutil',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (False, 'Disabled')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='individualutil',
            name='util',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residential.utility'),
        ),
        migrations.AddField(
            model_name='mutualutil',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment'),
        ),
        migrations.AddField(
            model_name='mutualutil',
            name='util',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residential.utility'),
        ),
    ]
