# Generated by Django 3.1.8 on 2021-04-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='apartments_number',
            new_name='apartments_capacity',
        ),
    ]
