# Generated by Django 3.1.7 on 2021-04-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0005_auto_20210415_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='cold_water_main_payment',
        ),
        migrations.RemoveField(
            model_name='building',
            name='gas_power_main_payment',
        ),
        migrations.RemoveField(
            model_name='building',
            name='heating_power_main_payment',
        ),
        migrations.RemoveField(
            model_name='building',
            name='hot_water_main_payment',
        ),
    ]
