# Generated by Django 3.1.7 on 2021-03-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0025_auto_20210330_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualutil',
            name='util_type',
        ),
        migrations.RemoveField(
            model_name='mutualutil',
            name='util_type',
        ),
        migrations.AddField(
            model_name='utility',
            name='util_type',
            field=models.CharField(choices=[('Mutual', 'Mutual'), ('Independent', 'Independent')], max_length=50, null=True),
        ),
    ]
