# Generated by Django 3.1.7 on 2021-03-31 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0026_auto_20210331_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='util_type',
        ),
        migrations.AddField(
            model_name='individualutil',
            name='util_type',
            field=models.CharField(default='Individual', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mutualutil',
            name='util_type',
            field=models.CharField(default='Mutual', max_length=50, null=True),
        ),
    ]
