# Generated by Django 3.1.7 on 2021-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0027_auto_20210331_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualutil',
            name='util_type',
        ),
        migrations.RemoveField(
            model_name='mutualutil',
            name='util_type',
        ),
        migrations.AddField(
            model_name='utility',
            name='util_type',
            field=models.CharField(choices=[('Mutual', 'Mutual'), ('Individual', 'Individual')], max_length=20, null=True),
        ),
    ]
