# Generated by Django 3.1.7 on 2021-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0028_auto_20210401_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='util_type',
            field=models.CharField(choices=[('Mutual', 'Mutual'), ('individual', 'Individual')], max_length=20, null=True),
        ),
    ]
